In [10]:
import pandas as pd
df=pd.read_csv("tested.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Q.1.  Find the number of passengers in each passenger class (Pclass).

In [8]:
df1=df.groupby("Pclass").size()
df1

Pclass
1    107
2     93
3    218
dtype: int64

Q.2. Find the average fare paid by passengers in each class.

In [12]:
df2=df.groupby("Pclass")["Fare"].mean()
df2

Pclass
1    94.280297
2    22.202104
3    12.459678
Name: Fare, dtype: float64

Q.3. Find the maximum and minimum age in each class.

In [13]:
df3=df.groupby("Pclass")["Age"].agg(["max", "min"])
df3

         max   min
Pclass
1       76.0  6.00
2       63.0  0.92
3       60.5  0.17

Q.4.  Find the number of male and female passengers.

In [14]:
df4=df.groupby("Sex").size()
df4

Sex
female    152
male      266
dtype: int64

Q.5. Find the average age of males and females.

In [15]:
df5=df.groupby("Sex")["Age"].mean()
df5

Sex
female    30.272362
male      30.272732
Name: Age, dtype: float64

Q.6.  Find the survival rate (mean of Survived) for each gender.

In [16]:
df6=df.groupby("Sex")["Survived"].mean()
df6

Sex
female    1.0
male      0.0
Name: Survived, dtype: float64

Q.7. Find the number of passengers grouped by Pclass and Sex

In [17]:
df7=df.groupby(["Pclass", "Sex"]).size()
df7

Pclass  Sex
1       female     50
        male       57
2       female     30
        male       63
3       female     72
        male      146
dtype: int64

Q.8. Find the average age for each combination of Pclass and Survived.

In [18]:
df8=df.groupby(["Pclass", "Survived"])["Age"].mean()
df8

Pclass  Survived
1       0           40.520000
        1           41.333333
2       0           30.940678
        1           24.376552
3       0           24.525104
        1           23.073400
Name: Age, dtype: float64

Q.9. Find the minimum age for each passenger class and gender.

In [20]:
df9=df.groupby(["Pclass", "Sex"])["Age"].min()
df9

Pclass  Sex
1       female    18.00
        male       6.00
2       female     0.92
        male       2.00
3       female     0.17
        male       0.33
Name: Age, dtype: float64

Q.10. Find the sum, mean, and count of fares for each class.

In [21]:
df10=df.groupby("Pclass")["Fare"].agg(["sum", "mean", "count"])
df10

               sum       mean  count
Pclass
1       10087.9918  94.280297    107
2        2064.7957  22.202104     93
3        2703.7501  12.459678    217